[env]
GIT_CLIFF_CONFIG = "{{ config_root }}/.github/cliff.toml"

[tools]
gh = "2.93.0"
uv = "0.11.19"
git-cliff = "2.13.1"
"pipx:ansible" = "13.7.0"
"pipx:ansible-core" = "2.21.0"
"pipx:ansible-lint" = "26.4.0"

[tasks.test]
run = "ansible-lint ."

[tasks.release]
file = ".github/release.sh"
