- name: Generate WireGuard keys
  register: wireguard_keys
  changed_when: false
  ansible.builtin.shell:
      executable: /bin/bash
      cmd: |
          set -o pipefail
          umask 077
          [ -f /etc/wireguard/preshared.key ] || wg genpsk | tee /etc/wireguard/preshared.key > /dev/null
          [ -f /etc/wireguard/private.key ] || wg genkey | tee /etc/wireguard/private.key > /dev/null
          [ -f /etc/wireguard/public.key ] || wg pubkey < /etc/wireguard/private.key | tee /etc/wireguard/public.key > /dev/null
          cat /etc/wireguard/preshared.key
          cat /etc/wireguard/private.key
          cat /etc/wireguard/public.key

- name: Generate WireGuard host
  ansible.builtin.set_fact:
      wireguard_host: "{{ wireguard_cidr | ansible.utils.nthhost(ansible_play_hosts_all.index(inventory_hostname) + 1) }}"

- name: Generate WireGuard routes
  register: wireguard_routes
  compute_routes:
      host: "{{ inventory_hostname }}"
      graph: "{{ wireguard_graph }}"

- name: Generate WireGuard config
  notify: Reload WireGuard
  ansible.builtin.template:
      src: templates/wg0.conf.j2
      dest: /etc/wireguard/wg0.conf
      owner: root
      group: root
      mode: "0644"
