- name: WireGuard install
  ansible.builtin.apt:
      name: [qrencode, wireguard, wireguard-tools]
      state: present
      update_cache: yes

- name: Wireguard enable
  ansible.builtin.service:
      name: wg-quick@wg0
      state: stopped
      enabled: yes
