- name: Ensure WireGuard config directory exists
  ansible.builtin.file:
      path: /etc/wireguard
      state: directory
      owner: root
      group: root
      mode: "0700"

- name: Install WireGuard packages (generic)
  ansible.builtin.package:
      name: "{{ wireguard_packages }}"
      state: present

- name: Load WireGuard kernel module immediately if available
  when: ansible_system == 'Linux'
  changed_when: false
  ansible.builtin.shell:
      cmd: modprobe wireguard || true
