- name: Load OS family specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
      params:
          paths: [vars]
          files:
              - "{{ ansible_distribution }}.yml"
              - "{{ ansible_os_family }}.yml"
              - main.yml

- name: Include WireGuard installation tasks
  ansible.builtin.include_tasks: install.yml

- name: Include WireGuard configuration tasks
  ansible.builtin.include_tasks: config.yml
