- name: Load OS family specific variables
  ansible.builtin.include_vars:
      file: "{{ role_path }}/vars/{{ ansible_os_family }}.yml"
      optional: true

- name: Include WireGuard installation tasks
  ansible.builtin.include_tasks: install.yml

- name: Include WireGuard configuration tasks
  ansible.builtin.include_tasks: config.yml
